"""empty message

Revision ID: e0ca9f57efb2
Revises: None
Create Date: 2016-06-04 01:55:55.240726

"""

# revision identifiers, used by Alembic.
revision = 'e0ca9f57efb2'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('your_name', sa.String(length=150), nullable=False),
    sa.Column('project_name', sa.String(), nullable=False),
    sa.Column('describe_purpose', sa.String(), nullable=False),
    sa.Column('website_design', sa.String(), nullable=False),
    sa.Column('project_budget', sa.Text(), nullable=False),
    sa.Column('project_deadline', sa.String(), nullable=False),
    sa.Column('finished_project', sa.String(), nullable=False),
    sa.Column('phone_number', sa.Text(), nullable=False),
    sa.Column('mobile_or_name_website', sa.String(), nullable=False),
    sa.Column('email_address', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_address')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job')
    ### end Alembic commands ###
